= Класс `File`

Класс `File`, определенный в пакете `java.io`, не работает напрямую с потоками. Его задачей является управление информацией о файлах и директориях. Хотя на уровне операционной системы файлы и директории отличаются, но в Java они описываются одним классом `File`.

В зависимости от того, что должен представлять объект `File` - файл или директория, мы можем использовать один из конструкторов для создания объекта:

* `File(String путь_к_директории)`
* `File(String путь_к_директории, String имя_файла)`
* `File(File каталог, String имя_файла)`

Например:

[source, java]
----
// создаем объект File для директории
File dir1 = new File("C://SomeDir");
// создаем объекты для файлов, которые находятся в директории
File file1 = new File("C://SomeDir", "Hello.txt");
File file2 = new File(dir1, "Hello2.txt");
----

Класс `File` имеет ряд методов, которые позволяют управлять файлами и директориями. Рассмотрим некоторые из них:

* `boolean createNewFile()` создает новый файл по пути, который передан в конструктор. В случае удачного создания возвращает `true`, иначе `false`
* `boolean delete()` удаляет директорию или файл по пути, который передан в конструктор. При удачном удалении возвращает `true`
* `boolean exists()` проверяет, существует ли по указанному в конструкторе пути файл или директория. И если файл или директория существует, то возвращает `true`, иначе возвращает `false`
* `String getAbsolutePath()` возвращает абсолютный путь для пути, переданного в конструктор объекта
* `String getName()` возвращает краткое имя файла или директории
* `String getParent()` возвращает имя родительской директории
* `boolean isDirectory()` возвращает значение `true`, если по указанному пути располагается директория
* `boolean isFile()` возвращает значение `true`, если по указанному пути находится файл
* `boolean isHidden()` возвращает значение `true`, если директория или файл являются скрытыми
* `long length()` возвращает размер файла в байтах
* `long lastModified()` возвращает время последнего изменения файла или директории. Значение представляет количество миллисекунд, прошедших с начала эпохи *Unix*
* `String[] list()` возвращает массив файлов и поддиректорий, которые находятся в определенной директории
* `File[] listFiles()` возвращает массив файлов и поддиректорий, которые находятся в определенной директории
* `boolean mkdir()` создает новую директорию и при удачном создании возвращает значение `true`
* `boolean renameTo(File dest)` переименовывает файл или директорию

== Работа с директориями

Если объект `File` представляет директорию, то его метод `isDirectory()` возвращает `true`. И поэтому мы можем получить ее содержимое - вложенные поддиректории и файлы с помощью методов `list()` и `listFiles()`. Получим все поддиректории и файлы в определенной директории:

[source, java]
----
import java.io.File;

public class Program {
    public static void main(String[] args) {
        // определяем объект для каталога
        File dir = new File("C://SomeDir");
        // если объект представляет каталог
        if (dir.isDirectory()) {
            // получаем все вложенные объекты в каталоге
            for (File item : dir.listFiles()) {
                if (item.isDirectory()) {
                    System.out.println(item.getName() + "  \t folder");
                } else {
                    System.out.println(item.getName() + "\t file");
                }
            }
        }
    }
}
----

Теперь выполним еще ряд операций с директорией, как удаление, переименование и создание:

[source, java]
----
import java.io.File;

public class Program {
    public static void main(String[] args) {
        // определяем объект для каталога
        File dir = new File("C://SomeDir//NewDir");
        boolean created = dir.mkdir();
        if (created) {
            System.out.println("Folder has been created");
        }
        // переименуем каталог
        File newDir = new File("C://SomeDir//NewDirRenamed");
        dir.renameTo(newDir);
        // удалим каталог
        boolean deleted = newDir.delete();
        if (deleted) {
            System.out.println("Folder has been deleted");
        }
    }
}
----

== Работа с файлами

Работа с файлами аналогична работе с директориями. Например, получим данные по одному из файлов и создадим еще один файл:

[source, java]
----
import java.io.File;
import java.io.IOException;

public class Program {
    public static void main(String[] args) {
        // определяем объект для каталога
        File myFile = new File("C://SomeDir//notes.txt");
        System.out.println("File name: " + myFile.getName());
        System.out.println("Parent folder: " + myFile.getParent());
        if (myFile.exists()) {
            System.out.println("File exists");
        } else {
            System.out.println("File not found");
        }

        System.out.println("File size: " + myFile.length());
        if (myFile.canRead()) {
            System.out.println("File can be read");
        } else {
            System.out.println("File can not be read");
        }

        if (myFile.canWrite()) {
            System.out.println("File can be written");
        } else {
            System.out.println("File can not be written");
        }
        // создадим новый файл
        File newFile = new File("C://SomeDir//MyFile");
        try {
            boolean created = newFile.createNewFile();
            if (created) {
                System.out.println("File has been created");
            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }
}
----

При создании нового файла метод `createNewFile()` в случае неудачи выбрасывает исключение `IOException`, поэтому нам надо его отлавливать, например, в блоке `try...catch`, как делается в примере выше.
