= Типы данных и переменные

Одной из основных особенностей *Java* является то, что данный язык является *строго типизированным*. А это значит, что каждая переменная и константа представляет определенный тип и данный тип строго определен. Тип данных определяет диапазон значений, которые может хранить переменная или константа.

== Базовые типы

Итак, рассмотрим систему встроенных базовых типов данных, которая используется для создания переменных в Java. А она представлена следующими типами.

`boolean`: хранит значение `true` или `false`

[source, java]
----
boolean isActive = false;
boolean isAlive = true;
----

`byte`: хранит целое число от `-128` до `127` и занимает `1 байт`

[source, java]
----
byte a = 3;
byte b = 8;
----

`short`: хранит целое число от `-32768` до `32767` и занимает `2 байта`

[source, java]
----
short a = 3;
short b = 8;
----

`int`: хранит целое число от `-2147483648` до `2147483647` и занимает `4 байта`

[source, java]
----
int a = 4;
int b = 9;
----

`long`: хранит целое число от `-9 223 372 036 854 775 808` до `9 223 372 036 854 775 807` и занимает `8 байт`

[source, java]
----
long a = 5;
long b = 10;
----

`double`: хранит число с плавающей точкой от `±4.9*10-324` до `±1.8*10308` и занимает `8 байт`

[source, java]
----
double x = 8.5;
double y = 2.7;
----

В качестве разделителя целой и дробной части в дробных литералах используется *ТОЧКА*.

`float`: хранит число с плавающей точкой от `-3.4*1038` до `3.4*1038` и занимает `4 байта`

[source, java]
----
float x = 8.5F;
float y = 2.7F;
----

`char`: хранит одиночный символ в кодировке *Unicode* и занимает `2 байта`, поэтому диапазон хранимых значений от `0` до `65536`

При этом переменная может принимать только те значения, которые соответствуют ее типу. Если переменная предствляет целочисленный тип, то она не может хранить дробные числа.

=== Целые числа

Все целочисленные литералы, например, `10`, `4`, `-5`, воспринимаются как значения типа `int`, однако мы можем присваивать целочисленные литералы другим целочисленным типам: `byte`, `long`, `short`. В этом случае Java автоматически осуществляет соответствующие преобразования:

[source, java]
----
byte a = 1;
short b = 2;
long c = 2121;
----

Как правило, значения для целочисленных переменных задаются в десятичной системе счисления, однако мы можем применять и другие системы исчисления. Например:

[source, java]
----
int num111 = 0x6F; // 16-тиричная система, число 111
int num8 = 010; // 8-ричная система, число 8
int num13 = 0b1101; // 2-ичная система, число 13
----

Для задания шестнадцатеричного значения после символов `0x` указывается число в шестнадцатеричном формате. Таким же образом восьмеричное значение указывается после символа `0`, а двоичное значение - после символов `0b`.

Также целые числа поддерживают разделение разрядов числа с помощью знака подчеркивания:

[source, java]
----
int x = 123_456;
int y = 234_567__789;
System.out.println(x); // 123456
System.out.println(y); // 234567789
----

=== Числа с плавающей точкой

При присвоении переменной типа `float` дробного литерала с плавающей точкой, например, `3.1`, `4.5` и т.д., Java автоматически рассматривает этот литерал как значение типа `double`. И чтобы указать, что данное значение должно рассматриваться как `float`, нам надо использовать суффикс `f`:

[source, java]
----
float fl = 30.6f;
double db = 30.6;
----

И хотя в данном случае обе переменных имеют практически одно значения, но эти значения будут по-разному рассматриваться и будут занимать разное место в памяти.

== Ссылочные типы

Все остальные за исключением примитивных. Если быть точным, то любой `Object`.

== Переменные

Для хранения данных в программе предназначены переменные. Переменная представляет именнованную область памяти, которая хранит значение определенного типа. Каждая переменная имеет тип, имя и значение. Тип определяет, какую информацию может хранить переменная или диапазон допустимых значений.

Переменные объявляются следующим образом:

[source, java]
----
тип_данных имя_переменной;
----

Например, определим переменную, которая будет называться `x` и будет иметь тип `int`:

[source, java]
----
int x;
----

В этом выражении мы объявляем переменную `x` типа `int`. То есть `x` будет хранить некоторое число не больше `4 байт`.

В качестве имени переменной может выступать любое произвольное название, которое удовлетворяет следующим требованиям:

* имя может содержать любые алфавитно-цифровые символы, а также знак подчеркивания, при этом первый символ в имени не должен быть цифрой
* в имени не должно быть знаков пунктуации и пробелов
* имя не может быть ключевым словом языка Java

Кроме того, при объявлении и последующем использовании надо учитывать, что *Java - регистрозависимый язык*, поэтому следующие объявления `int num;` и `int NUM;` будут представлять две разных переменных.

Объявив переменную, мы можем присвоить ей значений:

[source, java]
----
int x; // объявление переменной
x = 10; // присвоения значения
System.out.println(x); // 10
----

Также можно привоить значение переменной при ее объявлении. Этот процесс называется инициализацией:

[source, java]
----
int x = 10; // объявление и инициализация переменной
System.out.println(x); // 10
----

Если мы не присвоим переменной значение до ее использования, то мы можем получить ошибку, например, в следующем случае:

[source, java]
----
int x;
System.out.println(x);
----

Через запятую можно объявить сразу несколько переменных одного типа:

[source, java]
----
int x, y;
x = 10;
y = 25;
System.out.println(x); // 10
System.out.println(y); // 25
----

Также можно их сразу инициализировать:

[source, java]
----
int x = 8, y = 15;
System.out.println(x); // 8
System.out.println(y); // 15
----

Отличительной особенностью переменных является то, что мы можем в процессе работы программы изменять их значение:

[source, java]
----
int x = 10;
System.out.println(x); // 10
x = 25;
System.out.println(x); // 25
----

=== Ключевое слово var

Начиная с Java 10 в язык было добавлено ключевое слово `var`, которое также позволяет определять переменную:

[source, java]
----
var x = 10;
System.out.println(x); // 10
----

Слово `var` ставится вместо типа данных, а сам тип переменной выводится из того значения, которое ей присваивается. Например, переменой `x` приваивается число `10`, значит, переменная будет представлять тип `int`.

Но если переменная объявляется с помощью `var`, то мы обязательно должны инициализировать ее, то есть предоставить ей начальное значение, иначе мы получим ошибку, как, например, в следующм случае:

[source, java]
----
var x; // ! Ошибка, переменная не инициализирована
x = 10;
----

== Использование суффиксов

Как правило, значения для целочисленных переменных задаются в десятичной системе счисления, однако мы можем применять и другие системы исчисления. Например:

[source, java]
----
int num111 = 0x6F; // 16-тиричная система, число 111
int num8 = 010; // 8-ричная система, число 8
int num13 = 0b1101; // 2-ичная система, число 13
----

Для задания шестнадцатеричного значения после символов `0x` указывается число в шестнадцатеричном формате. Таким же образом восьмеричное значение указывается после символа `0`, а двоичное значение — после символов `0b`.

При присвоении переменной типа `float` значения с плавающей точкой Java автоматически рассматривает это значение как объкт типа `double`. И чтобы указать, что данное значение должно рассматриваться как `float`, нам надо использовать суффикс `f`:

[source, java]
----
float fl = 30.6f;
double db = 30.6;
----

И хотя в данном случае обе переменных имеют практически одно значения, но эти значения будут по-разному рассматриваться и будут занимать разное место в памяти.

== Символы и строки

В качестве значения переменная символьного типа получает одиночный символ, заключенный в ординарные кавычки: `char ch='e';`. Кроме того, переменной символьного типа также можно присвоить целочисленное значение от `0` до `65536`. В этом случае переменная опять же будет хранить символ, а целочисленное значение будет указывать на номер символа в таблице символов `Unicode`. Например:

[source, java]
----
char ch=102; // символ 'f'
System.out.println(ch);
----

Еще одной формой задания символьных переменных является шестнадцатеричная форма: переменная получает значение в шестнадцатеричной форме, которое следует после символов `"\u"`. Например, `char ch='\u0066';` опять же будет хранить символ `'f'`.

Символьные переменные не стоит путать со строковыми, `'a'` не идентично `"a"`. Строковые переменные представляют объект `String`, который в отличие от char или int не является примитивным типов в Java:

[source, java]
----
String hello = "Hellow...";
System.out.println(hello);
----

== Константы

Кроме переменных, в Java для хранения данных можно использовать константы. В отличие от переменных константам можно присвоить значение только один раз. Константа объявляется также, как и переменная, только вначале идет ключевое слово `final`:

[source, java]
----
final int LIMIT = 5;
System.out.println(LIMIT); // 5
// LIMIT=57; // так мы уже не можем написать, так как LIMIT - константа
----

Как правило, константы имеют имена в *ВЕРХНЕМ_РЕГИСТРЕ*.

Константы позволяют задать такие переменные, которые не должны больше изменяться. Например, если у нас есть переменная для хранения числа `pi`, то мы можем объявить ее константой, так как ее значение постоянно.
