= Инкапсуляция

Казалось бы, почему бы не объявить все переменные и методы с модификатором `public`, чтобы они были доступны в любой точке программы вне зависимости от пакета или класса?

Возьмем, например, поле `age`, которое представляет возраст. Если другой класс имеет прямой доступ к этому полю, то есть вероятность, что в процессе работы программы ему будет передано некорректное значение, например, отрицательное число. Подобное изменение данных не является желательным. Либо же мы хотим, чтобы некоторые данные были достуны напрямую, чтобы их можно было вывести на консоль или просто узнать их значение.

В этой связи рекомендуется как можно больше ограничивать доступ к данным, чтобы защитить их от нежелательного доступа извне (как для получения значения, так и для его изменения). Использование различных модификаторов гарантирует, что данные не будут искажены или изменены не надлежащим образом. Подобное сокрытие данных внутри некоторой области видимости называется *инкапсуляцией*.

Так, как правило, вместо непосредственного использования полей, как правило, используют методы доступа. Например:

[source, java]
----
public class Program {
    public static void main(String[] args) {
        Person kate = new Person("Kate", 30, true);
        System.out.println(kate.getAge()); // 30
        kate.setAge(33);
        System.out.println(kate.getAge()); // 33
        kate.setAge(123450);
        System.out.println(kate.getAge()); // 33
    }
}

class Person {
    private String name;
    private int age;
    private boolean adult;

    public Person(String name, int age, boolean adult) {
        this.name = name;
        this.age = age;
        this.adult = adult;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        if (age > 0 && age < 110) {
            this.age = age;
        }
    }

    public boolean isAdult() {
        return this.adult;
    }

    public void setAdult(boolean adult) {
        this.adult = adult;
    }
}
----

И затем вместо непосредственной работы с полями `name` и `age` в классе `Person` мы будем работать с методами, которые устанавливает и возвращают значения этих полей. Методы `setName()`, `setAge()` и `setAdult()`, которые меняют состояние объекта, иногда называют *мьютейтерами* (*mutator*). А методы `getName()`, `getAge()` и `isAdult()`, с помощью которых получаем доступ к состоянию класса, называют *аксессерами* (*accessor*).

Причем в эти методы мы можем вложить дополнительную логику. Например, в данном случае при изменении возраста производится проверка, насколько соответствует новое значение допустимому диапазону.
