= Именование git-репозиториев.

На Git-hosting каждому репозиторию нужно имя, поэтому, естественно, он должен соответствовать следующим критериям:

* Описательный, т.е. однозначно описывать содержимое репозитория
* Удобочитаемый

Для многих проектов, которые используют Git, по их названию нельзя ничего сказать о них. Так может есть стандарт, которому нужно следовать? Ответ: нет. Поэтому следует придерживаться здравого смысла, а если быть точнее, название репозитория зависит от проекта и языка программирование, который используется для него.

Если проект предназначен для веб-сайтов, то можно использовать *domain name* как название проекта. Например:

* `http://domain.com`

    domain.com

* `http://sub.domain.com`

    sub.domain.com

Если проект разрабатывается на Java, то лучше использовать имя конечного *artifact* (`.war`,  `.jar`).

По умолчанию лучше использовать:

* строчные буквы
* дефисы (как разделители)

----
the-fellowship-of-the-ring
the-two-towers
the-return-of-the-king
----

== Клонирование git-repositories

* Клонирование *repository* в директорию с таким же названием как Git *project*:

[source,shell script]
----
git clone git@github.com:username/project-name.git
----

*  Клонирование *repository* в директорию с названием `project`:

[source,shell script]
----
git clone git@github.com:username/project-name.git project
----

*  Клонирование *repository* в текущую директорию (она должна быть пуста):

[source,shell script]
----
git clone git@github.com:username/project-name.git .
----
