= Аннотации

*Аннотации* представляют собой некую мета-информацию. Они не выполняют какого-либо действия сами по себе, но они могут предоставлять дополнительную информацию, которая может быть использована компилятором, различными утилитами сборки и генерации кода, а также они могут обрабатываться во время выполнения программы.

Аннотации предваряются символом `@`. Пример часто используемой аннотации `@Override`, которая указывает компилятору, что этот метод переопределяет базовый метод:

[source, java]
----
@Override
public void someMethod() {
    // ...
}
----

Аннотации могут иметь элементы:

[source, java]
----
@SuppressWarnings(value = "unchecked")
public void method() {
}
----

Если элементов много, то они разделяются запятой, если элемент только один, и его имя `value`, то его название можно не указывать:

[source, java]
----
@SuppressWarnings("unchecked")
void myMethod() {
}
----

== Объявление аннотаций

Предположим, что при объявлении каждого нового класса необходимо записывать в комментариях информацию об авторах в таком виде:

[source, java]
----
class Goblin {
    // author : John Clark
    // sprites : Izabella Simpson
    // sound : Michael Lermontov
    // code : Pushkin A.
    // createdAt : 2016-03-30
    // description : Goblin is lurking creature.
    // comments :

    // ... code
}
----

Можно записывать эту информацию с помощью аннотаций. Для этого вам сперва нужно объявить эту аннотацию:

[source, java]
----
@interface Monstr {
    String author();
    String sprites();
    String sound();
    String code();
    String createdAt() default "0000-00-00";
    String description();

    // Example of array use
    String[] comments();
}
----

Теперь можно применить его к нашему классу `Goblin`:

[source, java]
----
@Monstr(
    author="John Clark",
    sprites = "Izabella Simpson",
    sound = "Michael Lermontov",
    code = "Pushkin A.",
    createdAt = "2016-03-30",
    description = "Goblin is lurking creature",
    comments = {"lol", "gg", "Аффтар жжёт"}
)
class Goblin {
}
----

Обратите внимание на запись элементов аннотации (`author`, `sprites`, `sound`) и на запись массива элементов с использованием фигурных скобок (`comments`).

Можно использовать предопределённую аннотацию `@Documented`, чтобы наша аннотация попадала в документацию, сгенерированную утилитой *JavaDoc*:

[source, java]
----
import java.lang.annotation.Documented;

@Documented
@interface Monstr {
    String author();
    String sprites();
    String sound();
    String code();
    String createdAt() default "0000-00-00";
    String description();

    // Example of array use
    String[] comments();
}
----

== Предопределённые аннотации

=== `@Deprecated`

`@Deprecated` указывает, что элемент устарел и не должен использоваться. Компилятор Java генерирует предупреждение, если вы используете класс, метод или поле, помеченные аннотацией `@Deprecated`. Устаревший элемент должен быть также помечен тегом *JavaDoc* `@deprecated`:

[source, java]
----
/*
 * @deprecated
 * explanation of why it was deprecated
 */
 @Deprecated
 static void deprecatedMethod() { }
----

=== `@Override`

`@Override` указывает, что метод переопределяет метод базового класса. Эту аннотацию использовать не обязательно, но рекомендуется.

[source, java]
----
@Override
public int myMethod(double x) {
    // ...
}
----

Если метод с `@Override` не может корректно переопределить метод базового класса, то компилятор генерирует ошибку.

=== `@SuppressWarnings`

`@SuppressWarnings` подавляет предупреждения. Пример подавления предупреждения об устаревшем методе:

[source, java]
----
// Указываем компиляторе не генерировать
// предупреждение о использовании
// устаревшего метода.
@SuppressWarnings("deprecation")
void useDeprecatedMethod() {
    // Используем устаревший метод.
    objectOne.deprecatedMethod();
}
----

Каждое предупреждение принадлежит какой-либо категории. В спецификации Java описано две категории. В `@SupressWarnings` можно указывать несколько категорий:

[source, java]
----
@SuppressWarnings({"unchecked", "deprecation"})
----

Различные реализации компиляторов и различные IDE могут добавлять свои категории предупреждений. Неподдерживаемые названия категорий пропускаются при использовании `@SuppressWarnings`.

=== `@SafeVarargs`

`@SafeVarargs` применяется к методу или конструктору и указывает, что код не осуществляет потенциально опасных операций со своим `varargs`-параметром (параметр, принимающий произвольное число параметров).

=== `@FunctionalInterface`

`@FunctionalInterface` указывает, что это объявление типа будет функциональным интерфейсом Java 8.

== Мета-аннотации

Аннотации, применяемые к другим аннотациям, называются *мета-аннотациями*. Есть несколько мета-аннотаций в пакете `java.lang.annotation`:

=== `@Retention`

`@Retention` определяет, как аннотация будет сохранена:

* `RetentionPolicy.SOURCE` - аннотация будет только в исходном коде, и она будет игнорироваться компилятором.
* `RetentionPolicy.CLASS` - аннотация будет доступна компилятору, но но будет игнорироваться виртуальной машиной Java.
* `RetentionPolicy.RUNTIME` - аннотация будет сохраняться JVM и будет доступна во время выполнения.

=== `@Documented`

`@Documented` - указывает, что элементы, помеченные этой аннотацией, должны документироваться JavaDoc. По умолчанию аннотации не включаются в документацию.

=== `@Target`

`@Target` - указывает какие элементы можно помечать этой аннотацией:

* `ElementType.ANNOTATION_TYPE` - данная аннотация может быть применена к другой аннотации.
* `ElementType.CONSTRUCTOR` - может быть применена к конструктору.
* `ElementType.FIELD` - может быть применена к полю.
* `ElementType.LOCAL_VARIABLE` - может быть применена к локальной переменной.
* `ElementType.METHOD` - может быть применена к методу.
* `ElementType.PACKAGE` - может быть применена к пакету.
* `ElementType.PARAMETER` - может быть применена к параметрам метода.
* `ElementType.TYPE` - может быть применена классу, интерфейсу, аннотации или перечислению.

=== `@Inherited`

`@Inherited` — аннотация может быть унаследована от базового класса (по умолчанию не наследуются). Когда запрашивается аннотация класса, и у класса нет такой аннотации, то запрашивается аннотация базового класса. Эта аннотация может быть применена только к классам.

=== `@Repeatable`

`@Repeatable` - аннотация может быть применена несколько раз.

Допустим мы хотим применить аннотацию `@Author` несколько раз для указания нескольких авторов:

[source, java]
----
@Author("Petya")
@Author("Vasya")
@Author("Suslik")
class Goblin {
}
----

Тогда необходимо объявить такую аннотацию следующим образом:

[source, java]
----
import java.lang.annotation.Repeatable;

@Repeatable(Authors.class)
@interface Author {
    String value();
}
----

Обратите внимание, что добавлена аннотация `@Repeatable` с указанием `Authors.class`, который мы должны объявить как аннотацию с массивом аннотация `Author`:

[source, java]
----
@interface Authors{
    Author[] value();
}
----

Теперь можно указывать аннотацию `@Author` столько раз, сколько необходимо, для любого класса.
